/// Lightweight quiz metadata for home grid / routing without loading question banks.
///
/// Loaded from `assets/quiz_banks/quiz_catalog.json` (generated by
/// `scripts/validate_quiz_banks.dart`).
class QuizSummary {
  const QuizSummary({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.description,
    required this.difficulty,
    this.diagnosticTags = const [],
  });

  final String id;
  final String title;
  final String subtitle;
  final String description;
  final String difficulty;
  final List<String> diagnosticTags;

  factory QuizSummary.fromCatalogJson(Map<String, dynamic> map) {
    final idName = map['id'];
    if (idName is! String) {
      throw const FormatException('QuizSummary: missing field "id"');
    }
    final title = map['title'];
    final subtitle = map['subtitle'];
    final description = map['description'];
    final difficulty = map['difficulty'];
    final tagsRaw = map['diagnosticTags'];

    if (title is! String) {
      throw const FormatException('QuizSummary: missing field "title"');
    }
    if (subtitle is! String) {
      throw const FormatException('QuizSummary: missing field "subtitle"');
    }
    if (description is! String) {
      throw const FormatException('QuizSummary: missing field "description"');
    }
    if (difficulty is! String) {
      throw const FormatException('QuizSummary: missing field "difficulty"');
    }

    return QuizSummary(
      id: idName,
      title: title,
      subtitle: subtitle,
      description: description,
      difficulty: difficulty,
      diagnosticTags: tagsRaw is List
          ? [for (final t in tagsRaw) t as String]
          : const [],
    );
  }
}
