#!/usr/bin/env python3
"""Generate deterministic SQL seed data for the Cloudflare D1 quiz database."""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


REPO = Path(__file__).resolve().parent.parent
DATA_SRC_DIR = REPO / "data-src"
QUIZ_META_CSV = DATA_SRC_DIR / "quiz" / "quizzes.csv"
QUESTIONS_CSV = DATA_SRC_DIR / "quiz" / "questions.csv"
CHOICES_CSV = DATA_SRC_DIR / "quiz" / "choices.csv"
DEFAULT_OUTPUT = REPO / "cloudflare" / "d1" / "seed.generated.sql"


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def _split_pipe(value: str | None) -> list[str]:
    if not value:
        return []
    return [p.strip() for p in value.split("|") if p.strip()]


def _sql_string(value: str | None) -> str:
    if value is None or value == "":
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def _sql_required(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _sql_int(value: str | None) -> str:
    if value is None or value.strip() == "":
        return "NULL"
    return str(int(value.strip()))


def _insert(table: str, columns: list[str], values: list[str]) -> str:
    joined_columns = ", ".join(columns)
    joined_values = ", ".join(values)
    return f"INSERT INTO {table} ({joined_columns}) VALUES ({joined_values});"


def build_seed_sql() -> str:
    quiz_rows = _read_csv(QUIZ_META_CSV)
    question_rows = _read_csv(QUESTIONS_CSV)
    choice_rows = _read_csv(CHOICES_CSV)

    lines = [
        "-- Generated by tool/build_d1_seed.py. Do not edit by hand.",
        "DELETE FROM question_vocabulary;",
        "DELETE FROM question_grammar_points;",
        "DELETE FROM question_tags;",
        "DELETE FROM choices;",
        "DELETE FROM questions;",
        "DELETE FROM quiz_tags;",
        "DELETE FROM quizzes;",
    ]

    for display_order, row in enumerate(quiz_rows, start=1):
        quiz_id = row["quiz_id"].strip()
        lines.append(
            _insert(
                "quizzes",
                [
                    "id",
                    "title",
                    "subtitle",
                    "description",
                    "difficulty",
                    "display_order",
                    "published",
                ],
                [
                    _sql_required(quiz_id),
                    _sql_required(row["title"]),
                    _sql_required(row["subtitle"]),
                    _sql_required(row["description"]),
                    _sql_required(row["difficulty"]),
                    str(display_order),
                    "1",
                ],
            )
        )
        for tag_order, tag in enumerate(_split_pipe(row["diagnostic_tags"]), start=1):
            lines.append(
                _insert(
                    "quiz_tags",
                    ["quiz_id", "tag", "sort_order"],
                    [_sql_required(quiz_id), _sql_required(tag), str(tag_order)],
                )
            )

    for row in question_rows:
        quiz_id = row["quiz_id"].strip()
        question_id = row["question_id"].strip()
        lines.append(
            _insert(
                "questions",
                [
                    "quiz_id",
                    "id",
                    "sort_order",
                    "type",
                    "prompt",
                    "prompt_en",
                    "context",
                    "context_en",
                    "japanese",
                    "japanese_en",
                    "correct_answer_id",
                    "accepted_answers_json",
                    "explanation",
                    "explanation_en",
                    "jlpt_level",
                    "difficulty_score",
                    "review_status",
                    "review_notes",
                    "source",
                    "author",
                ],
                [
                    _sql_required(quiz_id),
                    _sql_required(question_id),
                    _sql_int(row["sort_order"]),
                    _sql_required(row["type"].strip() or "multipleChoice"),
                    _sql_required(row["prompt"]),
                    _sql_required(row["prompt_en"]),
                    _sql_string(row["context"].strip()),
                    _sql_string(row["context_en"].strip()),
                    _sql_required(row["japanese"]),
                    _sql_required(row["japanese_en"]),
                    _sql_required(row["correct_answer_id"].strip()),
                    _sql_required(
                        json.dumps(
                            _split_pipe(row.get("accepted_answers")),
                            separators=(",", ":"),
                        )
                    ),
                    _sql_required(row["explanation"]),
                    _sql_required(row["explanation_en"]),
                    _sql_string(row["jlpt_level"].strip()),
                    _sql_int(row["difficulty_score"]),
                    _sql_string(row["review_status"].strip()),
                    _sql_string(row["review_notes"].strip()),
                    _sql_string(row["source"].strip()),
                    _sql_string(row["author"].strip()),
                ],
            )
        )
        for tag_order, tag in enumerate(_split_pipe(row["diagnostic_tags"]), start=1):
            lines.append(
                _insert(
                    "question_tags",
                    ["quiz_id", "question_id", "tag", "sort_order"],
                    [
                        _sql_required(quiz_id),
                        _sql_required(question_id),
                        _sql_required(tag),
                        str(tag_order),
                    ],
                )
            )
        for gp_order, grammar_point in enumerate(
            _split_pipe(row["grammar_points"]), start=1
        ):
            lines.append(
                _insert(
                    "question_grammar_points",
                    ["quiz_id", "question_id", "grammar_point", "sort_order"],
                    [
                        _sql_required(quiz_id),
                        _sql_required(question_id),
                        _sql_required(grammar_point),
                        str(gp_order),
                    ],
                )
            )
        for vocab_order, vocabulary in enumerate(_split_pipe(row["vocabulary"]), start=1):
            lines.append(
                _insert(
                    "question_vocabulary",
                    ["quiz_id", "question_id", "vocabulary", "sort_order"],
                    [
                        _sql_required(quiz_id),
                        _sql_required(question_id),
                        _sql_required(vocabulary),
                        str(vocab_order),
                    ],
                )
            )

    for row in choice_rows:
        lines.append(
            _insert(
                "choices",
                [
                    "quiz_id",
                    "question_id",
                    "id",
                    "sort_order",
                    "label",
                    "label_en",
                    "explanation",
                    "explanation_en",
                ],
                [
                    _sql_required(row["quiz_id"].strip()),
                    _sql_required(row["question_id"].strip()),
                    _sql_required(row["choice_id"].strip()),
                    _sql_int(row["sort_order"]),
                    _sql_required(row["label"]),
                    _sql_string(row["label_en"].strip()),
                    _sql_string(row["explanation"].strip()),
                    _sql_string(row["explanation_en"].strip()),
                ],
            )
        )

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="SQL file to write. Defaults to cloudflare/d1/seed.generated.sql.",
    )
    args = parser.parse_args()

    output = args.output
    if not output.is_absolute():
        output = REPO / output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_seed_sql(), encoding="utf-8")
    print(f"Wrote {output.relative_to(REPO)}")


if __name__ == "__main__":
    main()
