# Generates assets/dictionary/japanese_lexicon.json (run from repo root):
#   python tool/gen_lexicon.py
import json
from pathlib import Path

def entry(surface, reading, pos, defs, jlpt=None, tags=None):
    o = {
        "surface": surface,
        "reading": reading,
        "partOfSpeech": pos,
        "definitions": defs if isinstance(defs, list) else [defs],
    }
    if jlpt:
        o["jlptLevel"] = jlpt
    if tags:
        o["tags"] = tags
    return o

def main():
    rows = []

    def add(**kw):
        rows.append(entry(**kw))

    # Verbs (dictionary + common forms)
    verbs = [
        ("食べる", "たべる", "to eat", "N5", ["ichidan", "common"]),
        ("食べます", "たべます", "to eat (polite)", "N5", ["ichidan", "polite"]),
        ("食べた", "たべた", "ate", "N5", ["ichidan", "past"]),
        ("食べない", "たべない", "do not eat", "N5", ["ichidan", "negative"]),
        ("見る", "みる", "to see; to watch", "N5", ["ichidan", "common"]),
        ("見ます", "みます", "to see (polite)", "N5", ["ichidan"]),
        ("見た", "みた", "saw", "N5", ["ichidan", "past"]),
        ("見られる", "みられる", "can see; be seen", "N4", ["ichidan", "potential"]),
        ("行く", "いく", "to go", "N5", ["godan", "common"]),
        ("行きます", "いきます", "to go (polite)", "N5", ["godan"]),
        ("行った", "いった", "went", "N5", ["godan", "past"]),
        ("行かない", "いかない", "do not go", "N5", ["godan"]),
        ("来る", "くる", "to come", "N5", ["irregular", "common"]),
        ("来ます", "きます", "to come (polite)", "N5", ["irregular"]),
        ("来た", "きた", "came", "N5", ["irregular"]),
        ("する", "する", "to do", "N5", ["irregular", "common"]),
        ("します", "します", "to do (polite)", "N5", ["irregular"]),
        ("した", "した", "did", "N5", ["irregular"]),
        ("しない", "しない", "do not do", "N5", ["irregular"]),
        ("できる", "できる", "can do; be able to", "N5", ["ichidan"]),
        ("なる", "なる", "to become", "N5", ["godan"]),
        ("ある", "ある", "to exist (inanimate); to have", "N5", ["godan"]),
        ("いる", "いる", "to exist (animate); to be", "N5", ["ichidan"]),
        ("言う", "いう", "to say", "N5", ["godan"]),
        ("話す", "はなす", "to speak", "N5", ["godan"]),
        ("聞く", "きく", "to hear; to listen", "N5", ["godan"]),
        ("待つ", "まつ", "to wait", "N5", ["godan"]),
        ("書く", "かく", "to write", "N5", ["godan"]),
        ("読む", "よむ", "to read", "N5", ["godan"]),
        ("買う", "かう", "to buy", "N5", ["godan"]),
        ("売る", "うる", "to sell", "N5", ["godan"]),
        ("取る", "とる", "to take", "N5", ["godan"]),
        ("使う", "つかう", "to use", "N5", ["godan"]),
        ("思う", "おもう", "to think", "N5", ["godan"]),
        ("知る", "しる", "to know", "N5", ["godan"]),
        ("分かる", "わかる", "to understand", "N5", ["godan"]),
        ("覚える", "おぼえる", "to remember; to learn", "N5", ["ichidan"]),
        ("忘れる", "わすれる", "to forget", "N5", ["ichidan"]),
        ("始める", "はじめる", "to begin", "N5", ["ichidan"]),
        ("終わる", "おわる", "to end", "N5", ["godan"]),
        ("続ける", "つづける", "to continue", "N4", ["ichidan"]),
        ("止まる", "とまる", "to stop (intr.)", "N4", ["godan"]),
        ("止める", "とめる", "to stop (tr.)", "N4", ["ichidan"]),
        ("入る", "はいる", "to enter", "N5", ["godan"]),
        ("入れる", "いれる", "to put in", "N5", ["ichidan"]),
        ("出る", "でる", "to leave; to appear", "N5", ["ichidan"]),
        ("出す", "だす", "to take out; to submit", "N5", ["godan"]),
        ("開く", "あく", "to open (intr.); to become open", "N5", ["godan"]),
        ("開ける", "あける", "to open (tr.)", "N5", ["ichidan"]),
        ("閉まる", "しまる", "to close (intr.)", "N5", ["godan"]),
        ("閉める", "しめる", "to close (tr.)", "N5", ["ichidan"]),
        ("始まる", "はじまる", "to begin (intr.)", "N5", ["godan"]),
        ("働く", "はたらく", "to work", "N5", ["godan"]),
        ("休む", "やすむ", "to rest", "N5", ["godan"]),
        ("教える", "おしえる", "to teach; to tell", "N5", ["ichidan"]),
        ("習う", "ならう", "to learn (from a teacher)", "N5", ["godan"]),
        ("練習する", "れんしゅうする", "to practice", "N5", ["irregular"]),
        ("勉強する", "べんきょうする", "to study", "N5", ["irregular"]),
        ("運転する", "うんてんする", "to drive", "N5", ["irregular"]),
        ("連絡する", "れんらくする", "to contact", "N4", ["irregular"]),
        ("確認する", "かくにんする", "to confirm", "N4", ["irregular"]),
        ("説明する", "せつめいする", "to explain", "N4", ["irregular"]),
        ("参加する", "さんかする", "to participate", "N4", ["irregular"]),
        ("対応する", "たいおうする", "to handle; to respond", "N3", ["irregular", "work"]),
        ("検討する", "けんとうする", "to consider; to examine", "N3", ["irregular", "work"]),
        ("変える", "かえる", "to change (tr.)", "N5", ["ichidan"]),
        ("変わる", "かわる", "to change (intr.)", "N5", ["godan"]),
        ("決める", "きめる", "to decide", "N5", ["ichidan"]),
        ("決まる", "きまる", "to be decided", "N5", ["godan"]),
        ("渡す", "わたす", "to hand over", "N5", ["godan"]),
        ("渡る", "わたる", "to cross", "N5", ["godan"]),
        ("返す", "かえす", "to return (something)", "N5", ["godan"]),
        ("返る", "かえる", "to return (intr.)", "N5", ["godan"]),
        ("送る", "おくる", "to send", "N5", ["godan"]),
        ("届ける", "とどける", "to deliver", "N5", ["ichidan"]),
        ("貸す", "かす", "to lend", "N5", ["godan"]),
        ("借りる", "かりる", "to borrow", "N5", ["ichidan"]),
        ("会う", "あう", "to meet", "N5", ["godan"]),
        ("助ける", "たすける", "to help", "N5", ["ichidan"]),
        ("集める", "あつめる", "to collect", "N5", ["ichidan"]),
        ("集まる", "あつまる", "to gather (intr.)", "N5", ["godan"]),
        ("調べる", "しらべる", "to investigate", "N5", ["ichidan"]),
        ("比べる", "くらべる", "to compare", "N5", ["ichidan"]),
        ("考える", "かんがえる", "to think (consider)", "N5", ["ichidan"]),
        ("残る", "のこる", "to remain", "N5", ["godan"]),
        ("残す", "のこす", "to leave behind", "N5", ["godan"]),
        ("足りる", "たりる", "to be enough", "N5", ["ichidan"]),
        ("足す", "たす", "to add", "N5", ["godan"]),
        ("建てる", "たてる", "to build", "N5", ["ichidan"]),
        ("立つ", "たつ", "to stand", "N5", ["godan"]),
        ("座る", "すわる", "to sit", "N5", ["godan"]),
        ("起きる", "おきる", "to wake up; to get up", "N5", ["ichidan"]),
        ("歌う", "うたう", "to sing", "N5", ["godan"]),
        ("遊ぶ", "あそぶ", "to play", "N5", ["godan"]),
        ("泳ぐ", "およぐ", "to swim", "N5", ["godan"]),
        ("走る", "はしる", "to run", "N5", ["godan"]),
        ("降る", "ふる", "to fall (rain/snow)", "N5", ["godan"]),
        ("吹く", "ふく", "to blow", "N5", ["godan"]),
        ("消える", "きえる", "to disappear", "N5", ["ichidan"]),
        ("消す", "けす", "to erase; to turn off", "N5", ["godan"]),
        ("死ぬ", "しぬ", "to die", "N5", ["godan"]),
        ("生きる", "いきる", "to live", "N5", ["ichidan"]),
        ("降りる", "おりる", "to get off; descend", "N5", ["ichidan"]),
        ("乗る", "のる", "to ride", "N5", ["godan"]),
        ("持つ", "もつ", "to hold; to have", "N5", ["godan"]),
        ("置く", "おく", "to put; to place", "N5", ["godan"]),
        ("曲がる", "まがる", "to turn (corner)", "N5", ["godan"]),
    ]
    for s, r, g, jlpt, tags in verbs:
        add(surface=s, reading=r, pos="verb", defs=g, jlpt=jlpt, tags=tags)

    nouns = [
        ("本", "ほん", "book", "N5", ["common"]),
        ("人", "ひと", "person", "N5", ["common"]),
        ("時", "とき", "time; when", "N5", ["common"]),
        ("日", "ひ", "day; sun", "N5", ["common"]),
        ("月", "つき", "moon; month", "N5", ["common"]),
        ("年", "ねん", "year", "N5", ["common"]),
        ("今", "いま", "now", "N5", ["common"]),
        ("今日", "きょう", "today", "N5", ["common"]),
        ("明日", "あした", "tomorrow", "N5", ["common"]),
        ("昨日", "きのう", "yesterday", "N5", ["common"]),
        ("先生", "せんせい", "teacher", "N5", ["common"]),
        ("学生", "がくせい", "student", "N5", ["common"]),
        ("駅", "えき", "station", "N5", ["common"]),
        ("会社", "かいしゃ", "company", "N5", ["work"]),
        ("仕事", "しごと", "work; job", "N5", ["work"]),
        ("部屋", "へや", "room", "N5", ["common"]),
        ("家", "いえ", "house", "N5", ["common"]),
        ("学校", "がっこう", "school", "N5", ["common"]),
        ("大学", "だいがく", "university", "N5", ["common"]),
        ("授業", "じゅぎょう", "class; lesson", "N5", ["common"]),
        ("試験", "しけん", "exam", "N5", ["common"]),
        ("問題", "もんだい", "problem; question", "N5", ["common"]),
        ("答え", "こたえ", "answer", "N5", ["common"]),
        ("質問", "しつもん", "question", "N5", ["common"]),
        ("意味", "いみ", "meaning", "N5", ["common"]),
        ("言葉", "ことば", "word; language", "N5", ["common"]),
        ("文", "ぶん", "sentence; text", "N5", ["common"]),
        ("語", "ご", "language; word", "N5", ["common"]),
        ("漢字", "かんじ", "kanji", "N5", ["common"]),
        ("平仮名", "ひらがな", "hiragana", "N5", ["common"]),
        ("片仮名", "かたかな", "katakana", "N5", ["common"]),
        ("国", "くに", "country", "N5", ["common"]),
        ("町", "まち", "town; city", "N5", ["common"]),
        ("道", "みち", "road; way", "N5", ["common"]),
        ("車", "くるま", "car", "N5", ["common"]),
        ("電車", "でんしゃ", "train", "N5", ["common"]),
        ("バス", "ばす", "bus", "N5", ["common"]),
        ("飛行機", "ひこうき", "airplane", "N5", ["common"]),
        ("船", "ふね", "ship", "N5", ["common"]),
        ("友だち", "ともだち", "friend", "N5", ["common"]),
        ("家族", "かぞく", "family", "N5", ["common"]),
        ("父", "ちち", "father", "N5", ["common"]),
        ("母", "はは", "mother", "N5", ["common"]),
        ("兄", "あに", "older brother", "N5", ["common"]),
        ("姉", "あね", "older sister", "N5", ["common"]),
        ("弟", "おとうと", "younger brother", "N5", ["common"]),
        ("妹", "いもうと", "younger sister", "N5", ["common"]),
        ("子ども", "こども", "child", "N5", ["common"]),
        ("男", "おとこ", "man; male", "N5", ["common"]),
        ("女", "おんな", "woman; female", "N5", ["common"]),
        ("名前", "なまえ", "name", "N5", ["common"]),
        ("年齢", "ねんれい", "age", "N5", ["common"]),
        ("〜歳", "さい", "years old (counter)", "N5", ["counter"]),
        ("一つ", "ひとつ", "one (thing)", "N5", ["counter"]),
        ("二つ", "ふたつ", "two (things)", "N5", ["counter"]),
        ("三つ", "みっつ", "three (things)", "N5", ["counter"]),
        ("四つ", "よっつ", "four (things)", "N5", ["counter"]),
        ("五つ", "いつつ", "five (things)", "N5", ["counter"]),
        ("匹", "ひき", "counter (small animals)", "N4", ["counter"]),
        ("台", "だい", "counter (machines)", "N4", ["counter"]),
        ("個", "こ", "counter (general)", "N4", ["counter"]),
        ("冊", "さつ", "counter (books)", "N4", ["counter"]),
        ("本", "ほん", "counter (long objects)", "N4", ["counter"]),
        ("枚", "まい", "counter (flat things)", "N4", ["counter"]),
        ("人", "にん", "counter (people)", "N4", ["counter"]),
        ("番", "ばん", "number; turn", "N4", ["common"]),
        ("目", "め", "〜th (ordinal suffix)", "N4", ["counter"]),
        ("半分", "はんぶん", "half", "N5", ["common"]),
        ("全部", "ぜんぶ", "all; entire", "N5", ["common"]),
        ("料理", "りょうり", "cooking; dish", "N5", ["common"]),
        ("朝ごはん", "あさごはん", "breakfast", "N5", ["common"]),
        ("昼ごはん", "ひるごはん", "lunch", "N5", ["common"]),
        ("晩ごはん", "ばんごはん", "dinner", "N5", ["common"]),
        ("水", "みず", "water", "N5", ["common"]),
        ("お茶", "おちゃ", "tea", "N5", ["common"]),
        ("コーヒー", "こーひー", "coffee", "N5", ["common"]),
        ("肉", "にく", "meat", "N5", ["common"]),
        ("魚", "さかな", "fish", "N5", ["common"]),
        ("野菜", "やさい", "vegetable", "N5", ["common"]),
        ("果物", "くだもの", "fruit", "N5", ["common"]),
        ("天気", "てんき", "weather", "N5", ["common"]),
        ("雨", "あめ", "rain", "N5", ["common"]),
        ("雪", "ゆき", "snow", "N5", ["common"]),
        ("風", "かぜ", "wind; cold (illness)", "N5", ["common"]),
        ("暑い", "あつい", "hot (weather)", "N5", ["i-adj"]),
        ("寒い", "さむい", "cold (weather)", "N5", ["i-adj"]),
        ("暖かい", "あたたかい", "warm", "N5", ["i-adj"]),
        ("涼しい", "すずしい", "cool (pleasant)", "N5", ["i-adj"]),
        ("新しい", "あたらしい", "new", "N5", ["i-adj"]),
        ("古い", "ふるい", "old (thing)", "N5", ["i-adj"]),
        ("大きい", "おおきい", "big", "N5", ["i-adj"]),
        ("小さい", "ちいさい", "small", "N5", ["i-adj"]),
        ("高い", "たかい", "high; expensive", "N5", ["i-adj"]),
        ("安い", "やすい", "cheap", "N5", ["i-adj"]),
        ("長い", "ながい", "long", "N5", ["i-adj"]),
        ("短い", "みじかい", "short", "N5", ["i-adj"]),
        ("広い", "ひろい", "wide; spacious", "N5", ["i-adj"]),
        ("狭い", "せまい", "narrow", "N5", ["i-adj"]),
        ("早い", "はやい", "early; fast", "N5", ["i-adj"]),
        ("遅い", "おそい", "late; slow", "N5", ["i-adj"]),
        ("近い", "ちかい", "near", "N5", ["i-adj"]),
        ("遠い", "とおい", "far", "N5", ["i-adj"]),
        ("多い", "おおい", "many", "N5", ["i-adj"]),
        ("少ない", "すくない", "few", "N5", ["i-adj"]),
        ("易しい", "やさしい", "easy; kind", "N5", ["i-adj"]),
        ("難しい", "むずかしい", "difficult", "N5", ["i-adj"]),
        ("白い", "しろい", "white", "N5", ["i-adj"]),
        ("黒い", "くろい", "black", "N5", ["i-adj"]),
        ("赤い", "あかい", "red", "N5", ["i-adj"]),
        ("青い", "あおい", "blue", "N5", ["i-adj"]),
        ("黄色い", "きいろい", "yellow", "N5", ["i-adj"]),
        ("良い", "よい", "good", "N5", ["i-adj"]),
        ("悪い", "わるい", "bad", "N5", ["i-adj"]),
        ("かわいい", "かわいい", "cute", "N5", ["i-adj"]),
        ("忙しい", "いそがしい", "busy", "N5", ["i-adj"]),
        ("楽しい", "たのしい", "fun", "N5", ["i-adj"]),
        ("寂しい", "さびしい", "lonely", "N5", ["i-adj"]),
        ("確認", "かくにん", "confirmation; checking", "N4", ["work"]),
        ("場合", "ばあい", "case; situation", "N4", ["common"]),
        ("関係", "かんけい", "relationship", "N4", ["common"]),
        ("理由", "りゆう", "reason", "N4", ["common"]),
        ("目的", "もくてき", "purpose", "N4", ["common"]),
        ("約束", "やくそく", "promise", "N4", ["common"]),
        ("連絡", "れんらく", "contact", "N4", ["work"]),
        ("予定", "よてい", "plan; schedule", "N4", ["common"]),
        ("用事", "ようじ", "errand; business", "N4", ["common"]),
        ("用事", "ようじ", "task", "N4", ["work"]),
        ("説明", "せつめい", "explanation", "N4", ["common"]),
        ("注意", "ちゅうい", "caution; attention", "N4", ["common"]),
        ("安全", "あんぜん", "safety", "N4", ["common"]),
        ("危険", "きけん", "danger", "N4", ["common"]),
        ("ルール", "るーる", "rule", "N4", ["common"]),
        ("規則", "きそく", "rule; regulation", "N4", ["work"]),
        ("承認", "しょうにん", "approval", "N3", ["work"]),
        ("報告", "ほうこく", "report", "N3", ["work"]),
        ("会議", "かいぎ", "meeting", "N4", ["work"]),
        ("課長", "かちょう", "section chief", "N4", ["work"]),
        ("部長", "ぶちょう", "department head", "N4", ["work"]),
        ("社長", "しゃちょう", "company president", "N4", ["work"]),
        ("社員", "しゃいん", "company employee", "N4", ["work"]),
        ("給料", "きゅうりょう", "salary", "N4", ["work"]),
        ("残業", "ざんぎょう", "overtime", "N4", ["work"]),
        ("休暇", "きゅうか", "vacation; leave", "N4", ["work"]),
        ("書類", "しょるい", "documents", "N4", ["work"]),
        ("資料", "しりょう", "materials; data", "N4", ["work"]),
        ("コピー", "こぴー", "copy", "N4", ["work"]),
        ("メール", "めーる", "email", "N4", ["work"]),
        ("電話", "でんわ", "telephone", "N5", ["common"]),
        ("番号", "ばんごう", "number", "N5", ["common"]),
        ("住所", "じゅうしょ", "address", "N5", ["common"]),
        ("地図", "ちず", "map", "N5", ["common"]),
        ("上手", "じょうず", "skillful", "N5", ["na-adj"]),
        ("下手", "へた", "unskillful", "N5", ["na-adj"]),
        ("有名", "ゆうめい", "famous", "N5", ["na-adj"]),
        ("大丈夫", "だいじょうぶ", "okay; all right", "N5", ["na-adj"]),
        ("便利", "べんり", "convenient", "N5", ["na-adj"]),
        ("不便", "ふべん", "inconvenient", "N5", ["na-adj"]),
        ("簡単", "かんたん", "simple", "N5", ["na-adj"]),
        ("大切", "たいせつ", "important", "N5", ["na-adj"]),
        ("必要", "ひつよう", "necessary", "N5", ["na-adj"]),
        ("無理", "むり", "impossible; unreasonable", "N5", ["na-adj"]),
        ("自由", "じゆう", "freedom; free", "N5", ["na-adj"]),
        ("静か", "しずか", "quiet", "N5", ["na-adj"]),
        ("賑やか", "にぎやか", "lively", "N5", ["na-adj"]),
        ("元気", "げんき", "healthy; energetic", "N5", ["na-adj"]),
        ("嫌い", "きらい", "dislike", "N5", ["na-adj"]),
        ("好き", "すき", "like; fond", "N5", ["na-adj"]),
        ("上手に", "じょうずに", "skillfully", "N5", ["adverb"]),
        ("ゆっくり", "ゆっくり", "slowly", "N5", ["adverb"]),
        ("たぶん", "たぶん", "probably", "N5", ["adverb"]),
        ("ぜひ", "ぜひ", "by all means", "N5", ["adverb"]),
        ("もちろん", "もちろん", "of course", "N5", ["adverb"]),
        ("特に", "とくに", "especially", "N5", ["adverb"]),
        ("別に", "べつに", "not particularly", "N5", ["adverb"]),
        ("全然", "ぜんぜん", "not at all (with neg.)", "N5", ["adverb"]),
        ("すぐ", "すぐ", "immediately", "N5", ["adverb"]),
        ("もう", "もう", "already", "N5", ["adverb"]),
        ("まだ", "まだ", "still; not yet", "N5", ["adverb"]),
        ("いつも", "いつも", "always", "N5", ["adverb"]),
        ("よく", "よく", "often; well", "N5", ["adverb"]),
        ("時々", "ときどき", "sometimes", "N5", ["adverb"]),
        ("は", "わ", "topic particle", "N5", ["particle"]),
        ("が", "が", "subject particle", "N5", ["particle"]),
        ("を", "を", "object particle", "N5", ["particle"]),
        ("に", "に", "to; at; in (particle)", "N5", ["particle"]),
        ("で", "で", "by means; at (particle)", "N5", ["particle"]),
        ("へ", "へ", "toward (particle)", "N5", ["particle"]),
        ("と", "と", "and; with (particle)", "N5", ["particle"]),
        ("も", "も", "also (particle)", "N5", ["particle"]),
        ("から", "から", "from; because", "N5", ["particle"]),
        ("まで", "まで", "until; as far as", "N5", ["particle"]),
        ("より", "より", "than; from", "N5", ["particle"]),
        ("だけ", "だけ", "only", "N5", ["particle"]),
        ("ほど", "ほど", "degree; about", "N5", ["particle"]),
        ("か", "か", "question particle; or", "N5", ["particle"]),
        ("ね", "ね", "right? (particle)", "N5", ["particle"]),
        ("よ", "よ", "I tell you (particle)", "N5", ["particle"]),
        ("の", "の", "possessive; nominalizer", "N5", ["particle"]),
        ("や", "や", "and (among others)", "N5", ["particle"]),
        ("など", "など", "and so on", "N5", ["particle"]),
        ("ばかり", "ばかり", "only; nothing but", "N4", ["particle"]),
        ("しか", "しか", "only (with neg.)", "N4", ["particle"]),
        ("こそ", "こそ", "precisely; for sure", "N4", ["particle"]),
        ("でも", "でも", "but; or even", "N5", ["particle"]),
        ("ては", "ては", "if; contrast", "N4", ["particle"]),
        ("には", "には", "for; in order to", "N4", ["particle"]),
    ]

    for item in nouns:
        if len(item) == 5:
            s, r, g, jlpt, tags = item
            pos = "noun"
            if "i-adj" in tags:
                pos = "i-adjective"
            elif "na-adj" in tags:
                pos = "na-adjective"
            elif "adverb" in tags:
                pos = "adverb"
            elif "particle" in tags:
                pos = "particle"
            elif "counter" in tags and s not in ("本", "人"):
                pos = "counter"
            add(surface=s, reading=r, pos=pos, defs=g, jlpt=jlpt, tags=tags)

    # Homonym example: 開く (intr) vs 開ける — already have both
    add(
        surface="日本語",
        reading="にほんご",
        pos="noun",
        defs=["Japanese language"],
        jlpt="N5",
        tags=["common"],
    )
    add(
        surface="英語",
        reading="えいご",
        pos="noun",
        defs=["English language"],
        jlpt="N5",
        tags=["common"],
    )
    add(
        surface="窓",
        reading="まど",
        pos="noun",
        defs=["window"],
        jlpt="N5",
        tags=["common"],
    )
    add(
        surface="ドア",
        reading="どあ",
        pos="noun",
        defs=["door"],
        jlpt="N5",
        tags=["common"],
    )
    add(
        surface="鍵",
        reading="かぎ",
        pos="noun",
        defs=["key; lock"],
        jlpt="N5",
        tags=["common"],
    )
    add(
        surface="授業中",
        reading="じゅぎょうちゅう",
        pos="noun",
        defs=["during class"],
        jlpt="N4",
        tags=["common"],
    )
    add(
        surface="文中",
        reading="ぶんちゅう",
        pos="noun",
        defs=["in the sentence; mid-sentence"],
        jlpt="N3",
        tags=["grammar"],
    )
    add(
        surface="敬語",
        reading="けいご",
        pos="noun",
        defs=["honorific language"],
        jlpt="N4",
        tags=["register"],
    )
    add(
        surface="丁寧語",
        reading="ていねいご",
        pos="noun",
        defs=["polite speech"],
        jlpt="N4",
        tags=["register"],
    )
    add(
        surface="普通体",
        reading="ふつうたい",
        pos="noun",
        defs=["plain form style"],
        jlpt="N4",
        tags=["register"],
    )
    add(
        surface="自動詞",
        reading="じどうし",
        pos="noun",
        defs=["intransitive verb"],
        jlpt="N3",
        tags=["grammar"],
    )
    add(
        surface="他動詞",
        reading="たどうし",
        pos="noun",
        defs=["transitive verb"],
        jlpt="N3",
        tags=["grammar"],
    )
    add(
        surface="目的語",
        reading="もくてきご",
        pos="noun",
        defs=["object (grammar)"],
        jlpt="N3",
        tags=["grammar"],
    )
    add(
        surface="主語",
        reading="しゅご",
        pos="noun",
        defs=["subject (grammar)"],
        jlpt="N3",
        tags=["grammar"],
    )
    add(
        surface="述語",
        reading="じゅつご",
        pos="noun",
        defs=["predicate"],
        jlpt="N3",
        tags=["grammar"],
    )
    add(
        surface="助詞",
        reading="じょし",
        pos="noun",
        defs=["particle"],
        jlpt="N5",
        tags=["grammar"],
    )
    add(
        surface="格助詞",
        reading="かくじょし",
        pos="noun",
        defs=["case particle"],
        jlpt="N4",
        tags=["grammar"],
    )
    add(
        surface="副助詞",
        reading="ふくじょし",
        pos="noun",
        defs=["adverbial particle"],
        jlpt="N4",
        tags=["grammar"],
    )
    add(
        surface="終助詞",
        reading="しゅうじょし",
        pos="noun",
        defs=["sentence-final particle"],
        jlpt="N4",
        tags=["grammar"],
    )
    add(
        surface="敬体",
        reading="けいたい",
        pos="noun",
        defs=["polite style (です／ます)"],
        jlpt="N4",
        tags=["register"],
    )
    add(
        surface="常体",
        reading="じょうたい",
        pos="noun",
        defs=["plain style"],
        jlpt="N4",
        tags=["register"],
    )
    add(
        surface="話し言葉",
        reading="はなしことば",
        pos="noun",
        defs=["spoken language"],
        jlpt="N3",
        tags=["register"],
    )
    add(
        surface="書き言葉",
        reading="かきことば",
        pos="noun",
        defs=["written language"],
        jlpt="N3",
        tags=["register"],
    )
    add(
        surface="文脈",
        reading="ぶんみゃく",
        pos="noun",
        defs=["context"],
        jlpt="N3",
        tags=["grammar"],
    )
    add(
        surface="省略",
        reading="しょうりゃく",
        pos="noun",
        defs=["omission; abbreviation"],
        jlpt="N3",
        tags=["grammar"],
    )
    add(
        surface="埋める",
        reading="うめる",
        pos="verb",
        defs=["to fill (a gap); to bury"],
        jlpt="N4",
        tags=["godan"],
    )
    add(
        surface="着く",
        reading="つく",
        pos="verb",
        defs=["to arrive"],
        jlpt="N5",
        tags=["godan"],
    )
    add(
        surface="着きました",
        reading="つきました",
        pos="verb",
        defs=["arrived (polite)"],
        jlpt="N5",
        tags=["polite"],
    )
    add(
        surface="読みます",
        reading="よみます",
        pos="verb",
        defs=["read (polite)"],
        jlpt="N5",
        tags=["polite"],
    )
    add(
        surface="役に立つ",
        reading="やくにたつ",
        pos="expression",
        defs=["to be useful"],
        jlpt="N4",
        tags=["common"],
    )
    add(
        surface="気をつける",
        reading="きをつける",
        pos="expression",
        defs=["to be careful"],
        jlpt="N4",
        tags=["common"],
    )
    add(
        surface="〜について",
        reading="について",
        pos="expression",
        defs=["about; concerning"],
        jlpt="N4",
        tags=["grammar"],
    )
    add(
        surface="〜によると",
        reading="によると",
        pos="expression",
        defs=["according to"],
        jlpt="N3",
        tags=["grammar"],
    )
    add(
        surface="〜かどうか",
        reading="かどうか",
        pos="expression",
        defs=["whether or not"],
        jlpt="N4",
        tags=["grammar"],
    )

    out_dir = Path("assets/dictionary")
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "japanese_lexicon.json"
    path.write_text(json.dumps(rows, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {len(rows)} entries to {path}")


if __name__ == "__main__":
    main()
