// Builds the conjugation rules map matching assets/data/conjugation_rules.json.
// After edits, run: dart run tool/export_conjugation_rules.dart

/// Godan verb stem endings (る … む) in rule order.
const godanBefore = ['る', 'つ', 'う', 'く', 'ぐ', 'す', 'ぬ', 'ぶ', 'む'];

List<Map<String, dynamic>> _gf(List<String> after) {
  assert(after.length == godanBefore.length);
  return [
    for (var i = 0; i < godanBefore.length; i++)
      {'before': godanBefore[i], 'after': after[i]},
  ];
}

/// Duplicate-row forms (e.g. te-form negative なくて / ないで).
List<Map<String, dynamic>> _gf2(List<String> afterPairs) {
  assert(afterPairs.length == godanBefore.length * 2);
  final out = <Map<String, dynamic>>[];
  for (var i = 0; i < godanBefore.length; i++) {
    final b = godanBefore[i];
    out.add({'before': b, 'after': afterPairs[i * 2]});
    out.add({'before': b, 'after': afterPairs[i * 2 + 1]});
  }
  return out;
}

Map<String, dynamic> _gc(List<Map<String, dynamic>> forms, {bool tetakei = false}) {
  return {
    'forms': forms,
    if (tetakei) 'tetakei': true,
  };
}

Map<String, dynamic> _ich(String after) => {
      'forms': [
        {'before': 'る', 'after': after},
      ],
    };

Map<String, dynamic> _ich2(String after1, String after2) => {
      'forms': [
        {'before': 'る', 'after': after1},
        {'before': 'る', 'after': after2},
      ],
    };

Map<String, dynamic> _res(String result) => {
      'forms': [
        {'result': result},
      ],
    };

Map<String, dynamic> _res2(String r1, String r2) => {
      'forms': [
        {'result': r1},
        {'result': r2},
      ],
    };

Map<String, dynamic> _suru(String after) => {
      'forms': [
        {'before': 'する', 'after': after},
      ],
    };

Map<String, dynamic> _na(List<Map<String, dynamic>> forms) => {'forms': forms};

/// Full rules JSON-serializable map.
Map<String, dynamic> buildConjugationRulesMap() {
  return {
    'godan': _godanGroup(),
    'ichidan': _ichidanGroup(),
    'iku': _ikuGroup(),
    'kuru': _kuruGroup(),
    'suru': _suruGroup(),
    'aru': _aruGroup(),
    'iru': _iruGroup(),
    'i-adjective': _iAdjGroup(),
    'ii': _iiGroup(),
    'na-adjective': _naAdjGroup(),
  };
}

Map<String, dynamic> _godanGroup() {
  return {
    'negative': _gc(_gf([
      'らない',
      'たない',
      'わない',
      'かない',
      'がない',
      'さない',
      'なない',
      'ばない',
      'まない',
    ])),
    'polite': _gc(_gf([
      'ります',
      'ちます',
      'います',
      'きます',
      'ぎます',
      'します',
      'にます',
      'びます',
      'みます',
    ])),
    'polite negative': _gc(_gf([
      'りません',
      'ちません',
      'いません',
      'きません',
      'ぎません',
      'しません',
      'にません',
      'びません',
      'みません',
    ])),
    'past': _gc(
      _gf(['った', 'った', 'った', 'いた', 'いだ', 'した', 'んだ', 'んだ', 'んだ']),
      tetakei: true,
    ),
    'past negative': _gc(_gf([
      'らなかった',
      'たなかった',
      'わなかった',
      'かなかった',
      'がなかった',
      'さなかった',
      'ななかった',
      'ばなかった',
      'まなかった',
    ])),
    'polite past': _gc(_gf([
      'りました',
      'ちました',
      'いました',
      'きました',
      'ぎました',
      'しました',
      'にました',
      'びました',
      'みました',
    ])),
    'polite past negative': _gc(_gf([
      'りませんでした',
      'ちませんでした',
      'いませんでした',
      'きませんでした',
      'ぎませんでした',
      'しませんでした',
      'にませんでした',
      'びませんでした',
      'みませんでした',
    ])),
    'te-form': _gc(
      _gf(['って', 'って', 'って', 'いて', 'いで', 'して', 'んで', 'んで', 'んで']),
      tetakei: true,
    ),
    'te-form negative': _gc(_gf2([
      'らなくて',
      'らないで',
      'たなくて',
      'たないで',
      'わなくて',
      'わないで',
      'かなくて',
      'かないで',
      'がなくて',
      'がないで',
      'さなくて',
      'さないで',
      'ななくて',
      'なないで',
      'ばなくて',
      'ばないで',
      'まなくて',
      'まないで',
    ])),
    'conditional': _gc(_gf([
      'ったら',
      'ったら',
      'ったら',
      'ったら',
      'いだら',
      'したら',
      'んだら',
      'んだら',
      'んだら',
    ])),
    'conditional negative': _gc(_gf([
      'らなかったら',
      'たなかったら',
      'わなかったら',
      'かなかったら',
      'がなかったら',
      'さなかったら',
      'ななかったら',
      'ばなかったら',
      'まなかったら',
    ])),
    'provisional': _gc(_gf([
      'れば',
      'てば',
      'えば',
      'けば',
      'げば',
      'せば',
      'ねば',
      'べば',
      'めば',
    ])),
    'provisional negative': _gc(_gf([
      'れなければ',
      'てなければ',
      'えなければ',
      'けなければ',
      'げなければ',
      'せなければ',
      'ねなければ',
      'べなければ',
      'めなければ',
    ])),
    'potential': _gc(_gf([
      'れる',
      'てる',
      'える',
      'ける',
      'げる',
      'せる',
      'ねる',
      'べる',
      'める',
    ])),
    'potential negative': _gc(_gf([
      'れない',
      'てない',
      'えない',
      'けない',
      'げない',
      'せない',
      'ねない',
      'べない',
      'めない',
    ])),
    'polite potential': _gc(_gf([
      'れます',
      'てます',
      'えます',
      'けます',
      'げます',
      'せます',
      'ねます',
      'べます',
      'めます',
    ])),
    'polite potential negative': _gc(_gf([
      'れません',
      'てません',
      'えません',
      'けません',
      'げません',
      'せません',
      'ねません',
      'べません',
      'めません',
    ])),
    'passive': _gc(_gf([
      'られる',
      'たれる',
      'われる',
      'かれる',
      'がれる',
      'される',
      'なれる',
      'ばれる',
      'まれる',
    ])),
    'passive negative': _gc(_gf([
      'られない',
      'たれない',
      'われない',
      'かれない',
      'がれない',
      'されない',
      'なれない',
      'ばれない',
      'まれない',
    ])),
    'passive past': _gc(_gf([
      'られた',
      'たれた',
      'われた',
      'かれた',
      'がれた',
      'された',
      'なれた',
      'ばれた',
      'まれた',
    ])),
    'passive past negative': _gc(_gf([
      'られなかった',
      'たれなかった',
      'われなかった',
      'かれなかった',
      'がれなかった',
      'されなかった',
      'なれなかった',
      'ばれなかった',
      'まれなかった',
    ])),
    'passive te-form': _gc(_gf([
      'られて',
      'たれて',
      'われて',
      'かれて',
      'がれて',
      'されて',
      'なれて',
      'ばれて',
      'まれて',
    ])),
    'polite passive': _gc(_gf([
      'られます',
      'たれます',
      'われます',
      'かれます',
      'がれます',
      'されます',
      'なれます',
      'ばれます',
      'まれます',
    ])),
    'polite passive negative': _gc(_gf([
      'られません',
      'たれません',
      'われません',
      'かれません',
      'がれません',
      'されません',
      'なれません',
      'ばれません',
      'まれません',
    ])),
    'polite passive past': _gc(_gf([
      'られました',
      'たれました',
      'われました',
      'かれました',
      'がれました',
      'されました',
      'なれました',
      'ばれました',
      'まれました',
    ])),
    'polite passive past negative': _gc(_gf([
      'られませんでした',
      'たれませんでした',
      'われませんでした',
      'かれませんでした',
      'がれませんでした',
      'されませんでした',
      'なれませんでした',
      'ばれませんでした',
      'まれませんでした',
    ])),
    'causative': _gc(_gf([
      'らせる',
      'たせる',
      'わせる',
      'かせる',
      'がせる',
      'させる',
      'なせる',
      'ばせる',
      'ませる',
    ])),
    'causative negative': _gc(_gf([
      'らせない',
      'たせない',
      'わせない',
      'かせない',
      'がせない',
      'させない',
      'なせない',
      'ばせない',
      'ませない',
    ])),
    'causative past': _gc(_gf([
      'らせた',
      'たせた',
      'わせた',
      'かせた',
      'がせた',
      'させた',
      'なせた',
      'ばせた',
      'ませた',
    ])),
    'causative past negative': _gc(_gf([
      'らせなかった',
      'たせなかった',
      'わせなかった',
      'かせなかった',
      'がせなかった',
      'させなかった',
      'なせなかった',
      'ばせなかった',
      'ませなかった',
    ])),
    'causative passive': _gc(_gf([
      'らせられる',
      'たせられる',
      'わせられる',
      'かせられる',
      'がせられる',
      'させられる',
      'なせられる',
      'ばせられる',
      'ませられる',
    ])),
    'causative passive negative': _gc(_gf([
      'らせられない',
      'たせられない',
      'わせられない',
      'かせられない',
      'がせられない',
      'させられない',
      'なせられない',
      'ばせられない',
      'ませられない',
    ])),
    'causative passive past': _gc(_gf([
      'らせられた',
      'たせられた',
      'わせられた',
      'かせられた',
      'がせられた',
      'させられた',
      'なせられた',
      'ばせられた',
      'ませられた',
    ])),
    'causative passive past negative': _gc(_gf([
      'らせられなかった',
      'たせられなかった',
      'わせられなかった',
      'かせられなかった',
      'がせられなかった',
      'させられなかった',
      'なせられなかった',
      'ばせられなかった',
      'ませられなかった',
    ])),
    'imperative': _gc(_gf(['れ', 'て', 'え', 'け', 'げ', 'せ', 'ね', 'べ', 'め'])),
    'imperative negative': _gc(_gf([
      'るな',
      'つな',
      'うな',
      'くな',
      'ぐな',
      'すな',
      'ぬな',
      'ぶな',
      'むな',
    ])),
    'progressive': _gc(
      _gf([
        'っている',
        'っている',
        'っている',
        'いている',
        'いでいる',
        'している',
        'んでいる',
        'んでいる',
        'んでいる',
      ]),
      tetakei: true,
    ),
    'progressive negative': _gc(
      _gf([
        'っていない',
        'っていない',
        'っていない',
        'いていない',
        'いでいない',
        'していない',
        'んでいない',
        'んでいない',
        'んでいない',
      ]),
      tetakei: true,
    ),
    'polite progressive': _gc(
      _gf([
        'っています',
        'っています',
        'っています',
        'いています',
        'いでいます',
        'しています',
        'んでいます',
        'んでいます',
        'んでいます',
      ]),
      tetakei: true,
    ),
    'polite progressive negative': _gc(
      _gf([
        'っていません',
        'っていません',
        'っていません',
        'いていません',
        'いでいません',
        'していません',
        'んでいません',
        'んでいません',
        'んでいません',
      ]),
      tetakei: true,
    ),
    'progressive past': _gc(
      _gf([
        'っていた',
        'っていた',
        'っていた',
        'いていた',
        'いでいた',
        'していた',
        'んでいた',
        'んでいた',
        'んでいた',
      ]),
      tetakei: true,
    ),
    'progressive past negative': _gc(
      _gf([
        'っていなかった',
        'っていなかった',
        'っていなかった',
        'いていなかった',
        'いでいなかった',
        'していなかった',
        'んでいなかった',
        'んでいなかった',
        'んでいなかった',
      ]),
      tetakei: true,
    ),
    'polite progressive past': _gc(
      _gf([
        'っていました',
        'っていました',
        'っていました',
        'いていました',
        'いでいました',
        'していました',
        'んでいました',
        'んでいました',
        'んでいました',
      ]),
      tetakei: true,
    ),
    'polite progressive past negative': _gc(
      _gf([
        'っていませんでした',
        'っていませんでした',
        'っていませんでした',
        'いていませんでした',
        'いでいませんでした',
        'していませんでした',
        'んでいませんでした',
        'んでいませんでした',
        'んでいませんでした',
      ]),
      tetakei: true,
    ),
    'desire': _gc(_gf([
      'りたい',
      'ちたい',
      'いたい',
      'きたい',
      'ぎたい',
      'したい',
      'にたい',
      'びたい',
      'みたい',
    ])),
    'desire negative': _gc(_gf([
      'りたくない',
      'ちたくない',
      'いたくない',
      'きたくない',
      'ぎたくない',
      'したくない',
      'にたくない',
      'びたくない',
      'みたくない',
    ])),
    'desire past': _gc(_gf([
      'りたかった',
      'ちたかった',
      'いたかった',
      'きたかった',
      'ぎたかった',
      'したかった',
      'にたかった',
      'びたかった',
      'みたかった',
    ])),
    'desire past negative': _gc(_gf([
      'りたくなかった',
      'ちたくなかった',
      'いたくなかった',
      'きたくなかった',
      'ぎたくなかった',
      'したくなかった',
      'にたくなかった',
      'びたくなかった',
      'みたくなかった',
    ])),
    'desire te-form': _gc(_gf([
      'りたくて',
      'ちたくて',
      'いたくて',
      'きたくて',
      'ぎたくて',
      'したくて',
      'にたくて',
      'びたくて',
      'みたくて',
    ])),
    'desire te-form negative': _gc(_gf([
      'りたくなくて',
      'ちたくなくて',
      'いたくなくて',
      'きたくなくて',
      'ぎたくなくて',
      'したくなくて',
      'にたくなくて',
      'びたくなくて',
      'みたくなくて',
    ])),
    'desire polite': _gc(_gf([
      'りたいです',
      'ちたいです',
      'いたいです',
      'きたいです',
      'ぎたいです',
      'したいです',
      'にたいです',
      'びたいです',
      'みたいです',
    ])),
    'desire polite negative': _gc(_gf([
      'りたくないです',
      'ちたくないです',
      'いたくないです',
      'きたくないです',
      'ぎたくないです',
      'したくないです',
      'にたくないです',
      'びたくないです',
      'みたくないです',
    ])),
    'desire polite past': _gc(_gf([
      'りたかったです',
      'ちたかったです',
      'いたかったです',
      'きたかったです',
      'ぎたかったです',
      'したかったです',
      'にたかったです',
      'びたかったです',
      'みたかったです',
    ])),
    'desire polite past negative': _gc(_gf([
      'りたくなかったです',
      'ちたくなかったです',
      'いたくなかったです',
      'きたくなかったです',
      'ぎたくなかったです',
      'したくなかったです',
      'にたくなかったです',
      'びたくなかったです',
      'みたくなかったです',
    ])),
    'volitional': _gc(_gf(['ろう', 'とう', 'おう', 'こう', 'ごう', 'そう', 'のう', 'ぼう', 'もう'])),
    'polite volitional': _gc(_gf([
      'りましょう',
      'ちましょう',
      'いましょう',
      'きましょう',
      'ぎましょう',
      'しましょう',
      'にましょう',
      'びましょう',
      'みましょう',
    ])),
  };
}

Map<String, dynamic> _ichidanGroup() {
  return {
    'negative': _ich('ない'),
    'polite': _ich('ます'),
    'polite negative': _ich('ません'),
    'past': _ich('た'),
    'past negative': _ich('なかった'),
    'polite past': _ich('ました'),
    'polite past negative': _ich('ませんでした'),
    'te-form': _ich('て'),
    'te-form negative': _ich2('なくて', 'ないで'),
    'conditional': _ich('たら'),
    'conditional negative': _ich('なかったら'),
    'provisional': _ich('れば'),
    'provisional negative': _ich('なければ'),
    'potential': _ich2('られる', 'れる'),
    'potential negative': _ich('られない'),
    'polite potential': _ich('られます'),
    'polite potential negative': _ich('られません'),
    'imperative': _ich('ろ'),
    'imperative negative': _ich('るな'),
    'passive': _ich('られる'),
    'passive negative': _ich('られない'),
    'passive past': _ich('られた'),
    'passive past negative': _ich('られなかった'),
    'passive te-form': _ich('られて'),
    'polite passive': _ich('られます'),
    'polite passive negative': _ich('られません'),
    'polite passive past': _ich('られました'),
    'polite passive past negative': _ich('られませんでした'),
    'causative': _ich('させる'),
    'causative negative': _ich('させない'),
    'causative past': _ich('させた'),
    'causative past negative': _ich('させなかった'),
    'causative passive': _ich('させられる'),
    'causative passive negative': _ich('させられない'),
    'causative passive past': _ich('させられた'),
    'causative passive past negative': _ich('させられなかった'),
    'progressive': _ich('ている'),
    'progressive negative': _ich('ていない'),
    'polite progressive': _ich('ています'),
    'polite progressive negative': _ich('ていません'),
    'progressive past': _ich('ていた'),
    'progressive past negative': _ich('ていなかった'),
    'polite progressive past': _ich('ていました'),
    'polite progressive past negative': _ich('ていませんでした'),
    'desire': _ich('たい'),
    'desire negative': _ich('たくない'),
    'desire past': _ich('たかった'),
    'desire past negative': _ich('たくなかった'),
    'desire te-form': _ich('たくて'),
    'desire te-form negative': _ich('たくなくて'),
    'desire polite': _ich('たいです'),
    'desire polite negative': _ich('たくないです'),
    'desire polite past': _ich('たかったです'),
    'desire polite past negative': _ich('たくなかったです'),
    'volitional': _ich('よう'),
    'polite volitional': _ich('ましょう'),
  };
}

Map<String, dynamic> _ikuGroup() {
  return {
    'negative': _res('行[い]かない'),
    'polite': _res('行[い]きます'),
    'polite negative': _res('行[い]きません'),
    'past': _res('行[い]った'),
    'past negative': _res('行[い]かなかった'),
    'polite past': _res('行[い]きました'),
    'polite past negative': _res('行[い]きませんでした'),
    'te-form': _res('行[い]って'),
    'te-form negative': _res2('行[い]かなくて', '行[い]かないで'),
    'conditional': _res('行[い]ったら'),
    'conditional negative': _res('行[い]かなかったら'),
    'provisional': _res('行[い]けば'),
    'provisional negative': _res('行[い]かなければ'),
    'potential': _res('行[い]ける'),
    'potential negative': _res('行[い]けない'),
    'polite potential': _res('行[い]けます'),
    'polite potential negative': _res('行[い]けません'),
    'imperative': _res('行[い]け'),
    'imperative negative': _res('行[い]くな'),
    'passive': _res('行[い]かれる'),
    'passive negative': _res('行[い]かれない'),
    'passive past': _res('行[い]かれた'),
    'passive past negative': _res('行[い]かれなかった'),
    'passive te-form': _res('行[い]かれて'),
    'polite passive': _res('行[い]かれます'),
    'polite passive negative': _res('行[い]かれません'),
    'polite passive past': _res('行[い]かれました'),
    'polite passive past negative': _res('行[い]かれませんでした'),
    'causative': _res('行[い]かせる'),
    'causative negative': _res('行[い]かせない'),
    'causative past': _res('行[い]かせた'),
    'causative past negative': _res('行[い]かせなかった'),
    'causative passive': _res('行[い]かせられる'),
    'causative passive negative': _res('行[い]かせられない'),
    'causative passive past': _res('行[い]かせられた'),
    'causative passive past negative': _res('行[い]かせられなかった'),
    'progressive': _res('行[い]っている'),
    'progressive negative': _res('行[い]っていない'),
    'polite progressive': _res('行[い]っています'),
    'polite progressive negative': _res('行[い]っていません'),
    'progressive past': _res('行[い]っていた'),
    'progressive past negative': _res('行[い]っていなかった'),
    'polite progressive past': _res('行[い]っていました'),
    'polite progressive past negative': _res('行[い]っていませんでした'),
    'desire': _res('行[い]きたい'),
    'desire negative': _res('行[い]きたくない'),
    'desire past': _res('行[い]きたかった'),
    'desire past negative': _res('行[い]きたくなかった'),
    'desire te-form': _res('行[い]きたくて'),
    'desire te-form negative': _res('行[い]きたくなくて'),
    'desire polite': _res('行[い]きたいです'),
    'desire polite negative': _res('行[い]きたくないです'),
    'desire polite past': _res('行[い]きたかったです'),
    'desire polite past negative': _res('行[い]きたくなかったです'),
    'volitional': _res('行[い]こう'),
    'polite volitional': _res('行[い]きましょう'),
  };
}

Map<String, dynamic> _kuruGroup() {
  return {
    'negative': _res('来[こ]ない'),
    'polite': _res('来[き]ます'),
    'polite negative': _res('来[き]ません'),
    'past': _res('来[き]た'),
    'past negative': _res('来[こ]なかった'),
    'polite past': _res('来[き]ました'),
    'polite past negative': _res('来[き]ませんでした'),
    'te-form': _res('来[き]て'),
    'te-form negative': _res2('来[こ]なくて', '来[こ]ないで'),
    'conditional': _res('来[き]たら'),
    'conditional negative': _res('来[こ]なかったら'),
    'provisional': _res('来[く]れば'),
    'provisional negative': _res('来[こ]なければ'),
    'potential': _res('来[こ]られる'),
    'potential negative': _res('来[こ]られない'),
    'polite potential': _res('来[こ]られます'),
    'polite potential negative': _res('来[こ]られません'),
    'imperative': _res('来[こ]い'),
    'imperative negative': _res('来[く]るな'),
    'passive': _res('来[こ]られる'),
    'passive negative': _res('来[こ]られない'),
    'passive past': _res('来[こ]られた'),
    'passive past negative': _res('来[こ]られなかった'),
    'passive te-form': _res('来[こ]られて'),
    'polite passive': _res('来[こ]られます'),
    'polite passive negative': _res('来[こ]られません'),
    'polite passive past': _res('来[こ]られました'),
    'polite passive past negative': _res('来[こ]られませんでした'),
    'causative': _res('来[こ]させる'),
    'causative negative': _res('来[こ]させない'),
    'causative past': _res('来[こ]させた'),
    'causative past negative': _res('来[こ]させなかった'),
    'causative passive': _res('来[こ]させられる'),
    'causative passive negative': _res('来[こ]させられない'),
    'causative passive past': _res('来[こ]させられた'),
    'causative passive past negative': _res('来[こ]させられなかった'),
    'progressive': _res('来[き]ている'),
    'progressive negative': _res('来[き]ていない'),
    'polite progressive': _res('来[き]ています'),
    'polite progressive negative': _res('来[き]ていません'),
    'progressive past': _res('来[き]ていた'),
    'progressive past negative': _res('来[き]ていなかった'),
    'polite progressive past': _res('来[き]ていました'),
    'polite progressive past negative': _res('来[き]ていませんでした'),
    'desire': _res('来[き]たい'),
    'desire negative': _res('来[き]たくない'),
    'desire polite': _res('来[き]たいです'),
    'desire polite negative': _res('来[き]たくないです'),
    'desire past': _res('来[き]たかった'),
    'desire past negative': _res('来[き]たくなかった'),
    'desire te-form': _res('来[き]たくて'),
    'desire te-form negative': _res('来[き]たくなくて'),
    'desire polite past': _res('来[き]たかったです'),
    'desire polite past negative': _res('来[き]たくなかったです'),
    'volitional': _res('来[こ]よう'),
    'polite volitional': _res('来[き]ましょう'),
  };
}

Map<String, dynamic> _suruGroup() {
  return {
    'negative': _suru('しない'),
    'polite': _suru('します'),
    'polite negative': _suru('しません'),
    'past': _suru('した'),
    'past negative': _suru('しなかった'),
    'polite past': _suru('しました'),
    'polite past negative': _suru('しませんでした'),
    'te-form': _suru('して'),
    'te-form negative': _na([
      {'before': 'する', 'after': 'しなくて'},
      {'before': 'する', 'after': 'しないで'},
    ]),
    'conditional': _suru('したら'),
    'conditional negative': _suru('しなかったら'),
    'provisional': _suru('すれば'),
    'provisional negative': _suru('しなければ'),
    'potential': _suru('できる'),
    'potential negative': _suru('できない'),
    'polite potential': _suru('できます'),
    'polite potential negative': _suru('できません'),
    'imperative': _suru('しろ'),
    'imperative negative': _suru('するな'),
    'passive': _suru('される'),
    'passive negative': _suru('されない'),
    'passive past': _suru('された'),
    'passive past negative': _suru('されなかった'),
    'passive te-form': _suru('されて'),
    'polite passive': _suru('されます'),
    'polite passive negative': _suru('されません'),
    'polite passive past': _suru('されました'),
    'polite passive past negative': _suru('されませんでした'),
    'causative': _suru('させる'),
    'causative negative': _suru('させない'),
    'causative past': _suru('させた'),
    'causative past negative': _suru('させなかった'),
    'causative passive': _suru('させられる'),
    'causative passive negative': _suru('させられない'),
    'causative passive past': _suru('させられた'),
    'causative passive past negative': _suru('させられなかった'),
    'progressive': _suru('している'),
    'progressive negative': _suru('していない'),
    'polite progressive': _suru('しています'),
    'polite progressive negative': _suru('していません'),
    'progressive past': _suru('していた'),
    'progressive past negative': _suru('していなかった'),
    'polite progressive past': _suru('していました'),
    'polite progressive past negative': _suru('していませんでした'),
    'desire': _suru('したい'),
    'desire negative': _suru('したくない'),
    'desire past': _suru('したかった'),
    'desire past negative': _suru('したくなかった'),
    'desire te-form': _suru('したくて'),
    'desire te-form negative': _suru('したくなくて'),
    'desire polite': _suru('したいです'),
    'desire polite negative': _suru('したくないです'),
    'desire polite past': _suru('したかったです'),
    'desire polite past negative': _suru('したくなかったです'),
    'volitional': _suru('しよう'),
    'polite volitional': _suru('しましょう'),
  };
}

Map<String, dynamic> _aruGroup() {
  return {
    'negative': _res('ない'),
    'polite': _res('あります'),
    'polite negative': _res('ありません'),
    'past': _res('あった'),
    'past negative': _res('なかった'),
    'polite past': _res('ありました'),
    'polite past negative': _res('ありませんでした'),
    'te-form': _res('あって'),
    'te-form negative': _res2('なくて', 'ないで'),
    'conditional': _res('あったら'),
    'conditional negative': _res('なかったら'),
    'provisional': _res('あれば'),
    'provisional negative': _res('なければ'),
    'potential': _res('あれる'),
    'potential negative': _res('あれない'),
    'polite potential': _res('あれます'),
    'polite potential negative': _res('あれません'),
    'imperative': _res('あれ'),
    'imperative negative': _res('あるな'),
    'passive': _res('あられる'),
    'passive negative': _res('あられない'),
    'passive past': _res('あられた'),
    'passive past negative': _res('あられなかった'),
    'passive te-form': _res('あられて'),
    'polite passive': _res('あられます'),
    'polite passive negative': _res('あられません'),
    'polite passive past': _res('あられました'),
    'polite passive past negative': _res('あられませんでした'),
    'causative': _res('あらせる'),
    'causative negative': _res('あらせない'),
    'causative past': _res('あらせた'),
    'causative past negative': _res('あらせなかった'),
    'causative passive': _res('あらせられる'),
    'causative passive negative': _res('あらせられない'),
    'causative passive past': _res('あらせられた'),
    'causative passive past negative': _res('あらせられなかった'),
    'volitional': _res('あろう'),
    'polite volitional': _res('ありましょう'),
  };
}

Map<String, dynamic> _iruGroup() {
  return {
    'negative': _res('いない'),
    'polite': _res('います'),
    'polite negative': _res('いません'),
    'past': _res('いた'),
    'past negative': _res('いなかった'),
    'polite past': _res('いました'),
    'polite past negative': _res('いませんでした'),
    'te-form': _res('いて'),
    'te-form negative': _res2('いなくて', 'いないで'),
    'conditional': _res('いたら'),
    'conditional negative': _res('いなかったら'),
    'provisional': _res('いれば'),
    'provisional negative': _res('いなければ'),
    'potential': _res('いられる'),
    'potential negative': _res('いられない'),
    'polite potential': _res('いられます'),
    'polite potential negative': _res('いられません'),
    'imperative': _na([
      {'result': 'いよ'},
      {'result': 'いろ'},
    ]),
    'imperative negative': _res('いるな'),
    'passive': _res('あられる'),
    'passive negative': _res('あられない'),
    'passive past': _res('あられた'),
    'passive past negative': _res('あられなかった'),
    'passive te-form': _res('あられて'),
    'polite passive': _res('あられます'),
    'polite passive negative': _res('あられません'),
    'polite passive past': _res('あられました'),
    'polite passive past negative': _res('あられませんでした'),
    'causative': _res('あらせる'),
    'causative negative': _res('あらせない'),
    'causative past': _res('あらせた'),
    'causative past negative': _res('あらせなかった'),
    'causative passive': _res('あらせられる'),
    'causative passive negative': _res('あらせられない'),
    'causative passive past': _res('あらせられた'),
    'causative passive past negative': _res('あらせられなかった'),
    'volitional': _res('あろう'),
    'polite volitional': _res('ありましょう'),
  };
}

Map<String, dynamic> _iAdjGroup() {
  return {
    'negative': _na([
      {'before': 'い', 'after': 'くない'},
    ]),
    'polite': _na([
      {'before': 'い', 'after': 'いです'},
    ]),
    'polite negative': _na([
      {'before': 'い', 'after': 'くないです'},
      {'before': 'い', 'after': 'くありません'},
    ]),
    'past': _na([
      {'before': 'い', 'after': 'かった'},
    ]),
    'past negative': _na([
      {'before': 'い', 'after': 'くなかった'},
    ]),
    'polite past': _na([
      {'before': 'い', 'after': 'かったです'},
    ]),
    'polite past negative': _na([
      {'before': 'い', 'after': 'くなかったです'},
      {'before': 'い', 'after': 'くありませんでした'},
    ]),
    'provisional': _na([
      {'before': 'い', 'after': 'ければ'},
    ]),
    'provisional negative': _na([
      {'before': 'い', 'after': 'くなければ'},
    ]),
  };
}

Map<String, dynamic> _iiGroup() {
  return {
    'negative': _res('良[よ]くない'),
    'polite': _res('いいです'),
    'polite negative': _res2('良[よ]くないです', '良[よ]くありません'),
    'past': _res('良[よ]かった'),
    'past negative': _res('良[よ]くなかった'),
    'polite past': _res('良[よ]かったです'),
    'polite past negative': _res2('良[よ]くなかったです', '良[よ]くありませんでした'),
    'provisional': _res('良[よ]ければ'),
    'provisional negative': _res('良[よ]くなければ'),
  };
}

Map<String, dynamic> _naAdjGroup() {
  return {
    'negative': _na([
      {'before': 'だ', 'after': 'ではない'},
      {'before': 'だ', 'after': 'じゃない'},
    ]),
    'polite': _na([
      {'before': 'だ', 'after': 'です'},
    ]),
    'polite negative': _na([
      {'before': 'だ', 'after': 'ではないです'},
      {'before': 'だ', 'after': 'じゃないです'},
      {'before': 'だ', 'after': 'ではありません'},
      {'before': 'だ', 'after': 'じゃありません'},
    ]),
    'past': _na([
      {'before': 'だ', 'after': 'だった'},
    ]),
    'past negative': _na([
      {'before': 'だ', 'after': 'ではなかった'},
      {'before': 'だ', 'after': 'じゃなかった'},
    ]),
    'polite past': _na([
      {'before': 'だ', 'after': 'でした'},
    ]),
    'polite past negative': _na([
      {'before': 'だ', 'after': 'ではなかったです'},
      {'before': 'だ', 'after': 'じゃなかったです'},
      {'before': 'だ', 'after': 'ではありませんでした'},
      {'before': 'だ', 'after': 'じゃありませんでした'},
    ]),
    'provisional': _na([
      {'before': 'だ', 'after': 'ならば'},
    ]),
    'provisional negative': _na([
      {'before': 'だ', 'after': 'じゃなければ'},
    ]),
  };
}
